### ISSUE TITLE
won't compile

### ISSUE THREAD

**Issue by jose1711** [ginkgo/pink-pony#6]
compilation terminates with:

In file included from /usr/include/sigc++-2.0/sigc++/signal_base.h:27:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from src/Widget.hh:10,
                 from src/Menu.hh:11,
                 from src/Menu.cc:1:
/usr/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of 'static T_return sigc::internal::slot_call1<T_functor, T_return, T_arg1>::call_it(sigc::internal::slot_rep*, int) [with T_functor = sigc::bound_mem_functor1<void, Menu, int>; T_return = void; T_arg1 = int]':
/usr/include/sigc++-2.0/sigc++/functors/slot.h:144:37:   required from 'static void* (* sigc::internal::slot_call1<T_functor, T_return, T_arg1>::address())(void*) [with T_functor = sigc::bound_mem_functor1<void, Menu, int>; T_return = void; T_arg1 = int; sigc::internal::hook = void* (*)(void*)]'
/usr/include/sigc++-2.0/sigc++/functors/slot.h:543:90:   required from 'sigc::slot1<T_return, T_arg1>::slot1(const T_functor&) [with T_functor = sigc::bound_mem_functor1<void, Menu, int>; T_return = void; T_arg1 = int]'
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1273:26:   required from 'sigc::slot<T_return, T_arg1, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::slot(const T_functor&) [with T_functor = sigc::bound_mem_functor1<void, Menu, int>; T_return = void; T_arg1 = int]'
src/Menu.cc:448:61:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:136:72: error: 'operator()' not defined
       return (typed_rep->functor_).SIGC_WORKAROUND_OPERATOR_PARENTHESES<type_trait_take_t<T_arg1>>
                                                                        ^
scons: *** [src/Menu.o] Error 1

**Comment by Gallaecio** [comment]
Sounds like you are building pink-pony with an old C++ standard while it requires C++11. How are you building it?

**Comment by jose1711** [comment]
sorry, somehow i managed to build it already. closing.
