### ISSUE TITLE
What do hearts do?

### ISSUE THREAD

**Issue by alexgleason** [ginkgo/pink-pony#7]
This has long been a question among my peers.

**Comment by ginkgo** [comment]
They give you a scoring point, just like you do when some other player loses. The players are ranked by the number of point they have. They are visualized as the small hearts rotating around your rank number in the HUD.

**Comment by alexgleason** [comment]
Thank you!

Quickly, I just want to say that Pink Pony has brought myself and our friends a lot of joy. Thanks for creating it and putting it out there! It's our go-to party game.
